name: DeathStorage
main: com.thoughtsofglought.deathstorage.DeathStorage
version: 1.0
description: Drops stored in a  linked chest when killed.
author: ThoughtsofGlought
softdepend:
commands:
 
permissions:
  